In [1]:
"""
1- Import the file named
Data Analyst_Sample.csv in Pandas
2- Explore the file with at least 3
common exploration methods in
Pandas
3- How many rows and columns the
data file has?
4- Which column names have missing
values and how many?
5- Remove missing values from
columns that contain Pandas object
datatype
6- Replace missing values by zero in
columns that contain numbers
7- Verify that no missing values are in
the data file
"""
#1- Import the file named Data Analyst_Sample.csv in Pandas

import pandas as pd #Allows Pandas to be used with 'pd' alias

das = pd.read_csv('Data_Analyst_Sample.csv') #Imports csv file as 'das'

In [2]:
#2- Explore the file with at least 3 common exploration methods in Pandas

print('Max rows:', pd.options.display.max_rows) #Max rows system will return in full (60 by default), otherwise only headers and first and last 5 rows
print(das) #Prints dataframe

Max rows: 60
                                           Campaign Name  Campaign ID  \
0      CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
1      CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
2      CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
3      CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
4      CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
...                                                  ...          ...
52476  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52477  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52478  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52479  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDis_Pr...     25362071
52480  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticVideo_...     24922332

                                               Placement        Date  \
0      BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  05/03/2021
1      BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  06/03/2021
2      BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  07/03/2021
3      BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  08/03/2021
4      BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  09/03/2021
...                                                  ...         ...
52476         ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  28/03/2021
52477         ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  29/03/2021
52478         ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  30/03/2021
52479         ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  31/03/2021
52480            ES_Smart_Fortwo_TTD_DkTbMb_Interest_30"  11/01/2021

       Impressions  Clicks  Cost  Video Completions  Find A Dealer Conversion  \
0             39.0       0  0.17                  0                         0
1             43.0       0  0.27                  0                         0
2             35.0       0  0.26                  0                         0
3             60.0       0  0.13                  0                         0
4             17.0       0  0.04                  0                         0
...            ...     ...   ...                ...                       ...
52476          0.0     347  0.00                  0                        51
52477          0.0      76  0.00                  0                        12
52478          0.0      45  0.00                  0                         5
52479          0.0      52  0.00                  0                         8
52480          1.0       0  0.01                  1                         0

       Online Brochure Download
0                             0
1                             0
2                             0
3                             0
4                             0
...                         ...
52476                        24
52477                         1
52478                         0
52479                         3
52480                         0

[52481 rows x 10 columns]

In [3]:
print(das.head(12)) #Prints first 12 rows of dataframe

                                        Campaign Name  Campaign ID  \
0   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
1   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
2   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
3   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
4   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
5   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
6   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
7   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
8   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
9   CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
10  CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887
11  CY21_Q1_LOC_BE_Mercedes_S-Class_ProgrammaticDi...     25347887

                                            Placement        Date  \
0   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  05/03/2021
1   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  06/03/2021
2   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  07/03/2021
3   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  08/03/2021
4   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  09/03/2021
5   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  10/03/2021
6   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  11/03/2021
7   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  12/03/2021
8   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  13/03/2021
9   BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  14/03/2021
10  BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  15/03/2021
11  BE_Mercedes_S-Class_DV360_DkTbMb_Contextual_16...  16/03/2021

    Impressions  Clicks  Cost  Video Completions  Find A Dealer Conversion  \
0          39.0       0  0.17                  0                         0
1          43.0       0  0.27                  0                         0
2          35.0       0  0.26                  0                         0
3          60.0       0  0.13                  0                         0
4          17.0       0  0.04                  0                         0
5          26.0       0  0.24                  0                         0
6           4.0       0  0.02                  0                         0
7          19.0       0  0.10                  0                         0
8          47.0       0  0.17                  0                         0
9          71.0       0   NaN                  0                         0
10         64.0       0  0.11                  0                         0
11         72.0       0   NaN                  0                         0

    Online Brochure Download
0                          0
1                          0
2                          0
3                          0
4                          0
5                          0
6                          0
7                          0
8                          0
9                          0
10                         0
11                         0

In [4]:
print(das.tail(12)) #Prints last 12 rows of dataframe

                                           Campaign Name  Campaign ID  \
52469  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52470  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52471  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52472  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52473  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52474  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52475  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52476  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52477  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52478  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDispla...     25362071
52479  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticDis_Pr...     25362071
52480  CY21_Q1_LOC_ES_Smart_Fortwo_ProgrammaticVideo_...     24922332

                                        Placement        Date  Impressions  \
52469  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  21/03/2021          0.0
52470  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  22/03/2021          0.0
52471  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  23/03/2021          0.0
52472  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  24/03/2021          0.0
52473  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  25/03/2021          0.0
52474  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  26/03/2021          0.0
52475  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  27/03/2021          0.0
52476  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  28/03/2021          0.0
52477  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  29/03/2021          0.0
52478  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  30/03/2021          0.0
52479  ES_Smart_Fortwo_TTD_TbMb_Contextual_728x90  31/03/2021          0.0
52480     ES_Smart_Fortwo_TTD_DkTbMb_Interest_30"  11/01/2021          1.0

       Clicks  Cost  Video Completions  Find A Dealer Conversion  \
52469      47  0.00                  0                         3
52470      63  0.00                  0                         7
52471      56  0.00                  0                         9
52472      38  0.00                  0                         1
52473      56  0.00                  0                         7
52474      56  0.00                  0                         7
52475      66  0.00                  0                         7
52476     347  0.00                  0                        51
52477      76  0.00                  0                        12
52478      45  0.00                  0                         5
52479      52  0.00                  0                         8
52480       0  0.01                  1                         0

       Online Brochure Download
52469                         3
52470                         2
52471                         2
52472                         0
52473                         4
52474                         1
52475                         1
52476                        24
52477                         1
52478                         0
52479                         3
52480                         0

In [5]:
das.describe() #Shows basic descriptive statistics for numeric columns

,Campaign ID,Impressions,Clicks,Cost,Video Completions,Find A Dealer Conversion,Online Brochure Download
count,5.248100e+04,5.245100e+04,52481.000000,52458.000000,52481.000000,52481.000000,52481.000000
mean,2.537639e+07,4.841354e+03,29.774356,28.538750,995.629104,3.051790,1.231589
std,4.054270e+04,2.562214e+04,176.324974,167.347141,5552.026890,21.285292,8.802559
min,2.492233e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.533641e+07,6.100000e+01,0.000000,0.270000,0.000000,0.000000,0.000000
50%,2.536894e+07,4.120000e+02,1.000000,1.970000,0.000000,0.000000,0.000000
75%,2.541376e+07,2.258000e+03,4.000000,11.530000,172.000000,0.000000,0.000000
max,2.553608e+07,2.537059e+06,7662.000000,11826.480000,224248.000000,984.000000,435.000000

In [6]:
das.describe(include = object) #Descriptive statistice for objects

,Campaign Name,Placement,Date
count,52445,52481,52448
unique,49,421,56
top,CY21_Q1_LOC_BE_Mercedes_C-Class_ProgrammaticDi...,"ITALIA_SMART_DV360_30""",05/03/2021
freq,4894,946,1380

In [7]:
#3- How many rows and columns the data file has?
#4- Which column names have missing values and how many?

print(das.info()) #Prints dataframe information 

#Number of rows and columns: 52481 entries (rows), 10 columns

#Column names with missing values (52481 - non-null count): 
#'0 Campaign Name': 36 rows with missing values
#'3 Date': 33 rows with missing values
#'4 Impressions': 30 rows with missing values
#'6 Cost': 23 rows with missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52481 entries, 0 to 52480
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Campaign Name             52445 non-null  object
 1   Campaign ID               52481 non-null  int64
 2   Placement                 52481 non-null  object
 3   Date                      52448 non-null  object
 4   Impressions               52451 non-null  float64
 5   Clicks                    52481 non-null  int64
 6   Cost                      52458 non-null  float64
 7   Video Completions         52481 non-null  int64
 8   Find A Dealer Conversion  52481 non-null  int64
 9   Online Brochure Download  52481 non-null  int64
dtypes: float64(2), int64(5), object(3)
memory usage: 4.0+ MB
None

In [33]:
"""
5- Remove missing values from
columns that contain Pandas object
datatype
"""

das2 = das.select_dtypes(include=['object']) #Only selects columns with datatype 'object' and puts them in new dataframe 'das2'
das2.dropna(inplace = True) #'dropna' removes empty rows, 'inplace = True' will not return new dataframe but remove all rows containing null values from original dataframe
print(das2.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52412 entries, 0 to 52480
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Campaign Name  52412 non-null  object
 1   Placement      52412 non-null  object
 2   Date           52412 non-null  object
dtypes: object(3)
memory usage: 1.6+ MB
None

In [32]:
#6- Replace missing values by zero in columns that contain numbers
#7- Verify that no missing values are in the data file

das2 = das.select_dtypes(include=['number']) #Selects all number-based columns
das2.fillna(0, inplace = True) #'fillna' replaces empty values with '0'
print(das2.info()) #All non-null counts are the same as the number of rows, so no missing values in data file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52481 entries, 0 to 52480
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Campaign ID               52481 non-null  int64
 1   Impressions               52481 non-null  float64
 2   Clicks                    52481 non-null  int64
 3   Cost                      52481 non-null  float64
 4   Video Completions         52481 non-null  int64
 5   Find A Dealer Conversion  52481 non-null  int64
 6   Online Brochure Download  52481 non-null  int64
dtypes: float64(2), int64(5)
memory usage: 2.8 MB
None